In [17]:
import pandas as pd

In [18]:
df = pd.read_csv(r"C:\Users\56cha\Downloads\Mall_Customers.csv")

In [19]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [20]:
df.tail()

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [21]:
df.shape

(200, 5)

In [22]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='str')

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    str
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), str(1)
memory usage: 8.9 KB

In [24]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [25]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [26]:
df.duplicated().sum()

np.int64(0)

In [27]:
df.drop_duplicates(inplace=True)

print("Duplicates Removed")

Duplicates Removed

In [28]:
df["Age"]

0      19
1      21
2      20
3      23
4      31
       ..
195    35
196    45
197    32
198    32
199    30
Name: Age, Length: 200, dtype: int64

In [29]:
df[["Age", "Annual Income (k$)"]]

     Age  Annual Income (k$)
0     19                  15
1     21                  15
2     20                  16
3     23                  16
4     31                  17
..   ...                 ...
195   35                 120
196   45                 126
197   32                 126
198   32                 137
199   30                 137

[200 rows x 2 columns]

In [30]:
df[df["Age"] > 30]

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
4             5  Female   31                  17                      40
6             7  Female   35                  18                       6
8             9    Male   64                  19                       3
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
..          ...     ...  ...                 ...                     ...
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18

[138 rows x 5 columns]

In [31]:
df[df["Spending Score (1-100)"] > 80]

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
1             2    Male   21                  15                      81
7             8  Female   23                  18                      94
11           12  Female   35                  19                      99
19           20  Female   35                  23                      98
25           26    Male   29                  28                      82
29           30  Female   23                  29                      87
33           34    Male   18                  33                      92
35           36  Female   21                  33                      81
41           42    Male   24                  38                      92
123         124    Male   39                  69                      91
127         128    Male   40                  71                      95
135         136  Female   29                  73                      88
141         142    Male   32                  75                      93
143         144  Female   32                  76                      87
145         146    Male   28                  77                      97
149         150    Male   34                  78                      90
151         152    Male   39                  78                      88
155         156  Female   27                  78                      89
161         162  Female   29                  79                      83
163         164  Female   31                  81                      93
167         168  Female   33                  86                      95
173         174    Male   36                  87                      92
175         176  Female   30                  88                      86
179         180    Male   35                  93                      90
181         182  Female   32                  97                      86
183         184  Female   29                  98                      88
185         186    Male   30                  99                      97
189         190  Female   36                 103                      85
193         194  Female   38                 113                      91
199         200    Male   30                 137                      83

In [32]:
df["Age"].mean()

np.float64(38.85)

In [33]:
df["Annual Income (k$)"].max()

np.int64(137)

In [34]:
df["Spending Score (1-100)"].min()

np.int64(1)

In [35]:
df[df["Gender"] == "Male"].shape[0]

88

In [36]:
df[df["Gender"] == "Female"].shape[0]

112

In [37]:
df.to_csv("Cleaned_Mall_Customers.csv", index=False)

print("Dataset Saved Successfully!")

Dataset Saved Successfully!